src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *  @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    /**
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $lng;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->sold = false;
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string {
        $slugify = new Slugify();
        return $slugify->slugify($this->getTitle());
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): string {
        return number_format($this->getPrice(), 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string {
        return self::HEAT[$this->getHeat()];
    }
    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * Get the value of filename
     *
     * @return  string|null
     */ 
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set the value of filename
     *
     * @param  string|null  $filename
     *
     * @return  self
     */ 
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?Picture
    {
        return !$this->pictures->isEmpty() 
            ? $this->pictures->first()
            : null;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * Get })
     */ 
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * Set })
     *
     * @return  self
     */ 
    public function setPictureFiles($pictureFiles)
    {
        foreach ($pictureFiles as $pictureFile){
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getHeatChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true,
                'required' => false
            ])
            ->add('pictureFiles', FileType::class, [
                'required' => false,
                'multiple' => true
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('lat', HiddenType::class)
            ->add('lng', HiddenType::class)
            ->add('sold')
            //->add('created_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getHeatChoices() {
        $choices = Property::HEAT;
        $ouptut = [];
        foreach($choices as $key => $value){
            $output[$value] = $key;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository $repository
     */
    private $repository;

    public function __construct(PropertyRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/property", name="property.index")
     */
    public function index(Request $request, PaginatorInterface $paginator): Response {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/property/{slug}-{id}", name="property.show", requirements={ "slug": "[a-z0-9\-]*" })
     */
    public function show($slug, $id, Request $request, ContactNotification $notification): Response {
        $property = $this->repository->find($id);
        if ($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }
        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $notification->notify($contact);
            $this->addFlash('success', 'Votre message a bien été envoyé');
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }
        return $this->render('property/show.html.twig', [
            'current_menu' => 'properties',
            'property' => $property,
            'form' => $form->createView()
        ]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
  {% if property.picture %}
    <img src="{{ vich_uploader_asset(property.picture, 'imageFile') | imagine_filter('thumb') }}"
      class="card-img-top" alt=""
      style="width: 100%; height: auto"
    />
  {% else %}
    <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}"
      class="card-img-top" alt=""
      style="width: 100%; height: auto"
    />
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">
      <a href="{{ path('property.show', { slug: property.slug, id: property.id }) }}">
        {{ property.title }}
      </a>
    </h5>
    <p class="card-text">
      {{ property.description | nl2br }}
    </p>
    <p class="card-text">
      {{property.surface }} m² - {{ property.city }} ({{ property.postalCode }})
    </p>
    <div class="text-primary" style="font-size: 2rem; font-weight: bold">
      {{ property.formattedPrice }} €
    </div>
  </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Propriétés{% endblock %}

{% block body %}

  {{ form_start(form) }}
    <div class="form-row align-items-end">
      <div class="col">
        {{ form_row(form.minSurface) }}
      </div>
      <div class="col">
        {{ form_row(form.maxPrice) }}
      </div>
      <div class="col">
        {{ form_row(form.options) }}
      </div>
      <div class="col">
        {{ form_row(form.address, { id: 'search_address' }) }}
      </div>
      <div class="col">
        {{ form_row(form.distance) }}
      </div>
      <div class="col">
        <div class="form-group">
          <button class="btn btn-primary">Rechercher</button>
        </div>
      </div>
    </div>
  {{ form_end(form) }}

  <h1>Voir tous nos biens</h1>
  <div class="row">
    {% for property in properties %}
      <div class="col-md-4">
        {% include 'property/_property.html.twig' %}
      </div>
    {% endfor %}
  </div>
  <div class="pagination">
    {{ knp_pagination_render(properties) }}
  </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Propriété{% endblock %}

{% block body %}
  {% for message in app.flashes('success') %}
    <div class="alert alert-success">
      {{ message }}
    </div>
  {% endfor %}
  {% if not form.vars.valid %}
    <div class="alert alert-danger">
      Veuillez vérifier le formulaire de contact.
    </div>
  {% endif %}
  <div class="row">
    <div class="col-md-8">
      <div data-slider>
        {% if property.pictures is empty %}
          <img src="{{ '/images/properties/empty.jpg' | imagine_filter('medium') }}"
            class="" alt=""
            style="width: 100%; height: auto"
          />
        {% else %}
          {% for picture in property.pictures %}
            <img src="{{ vich_uploader_asset(picture, 'imageFile') | imagine_filter('medium') }}"
              class="" alt=""
              style="width: 100%; height: auto"
            />
          {% endfor %}
        {% endif %}
      </div>
    </div>
    <div class="col-md-4">
      <h1>{{ property.title }}</h1>
      <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
      <div class="text-primary" style="font-size: 2rem; font-weight: bold">
        {{ property.formattedPrice }} €
      </div>
      <a href="#" id="contactButton" class="btn btn-primary"
        {% if form.vars.submitted %}style="display: none"{% endif %}
      >Contacted l'agence</a>
      <div id="contactForm" class="mt-4"
        {% if not form.vars.submitted %}style="display: none"{% endif %}
      >
        {{ form_start(form) }}
          <div class="row">
            <div class="col">{{ form_row(form.firstname) }}</div>
            <div class="col">{{ form_row(form.lastname) }}</div>
          </div>
          <div class="row">
            <div class="col">{{ form_row(form.phone) }}</div>
            <div class="col">{{ form_row(form.email) }}</div>
          </div>
          {{ form_rest(form) }}
          <div class="form-group">
            <button class="btn btn-primary">Envoyer</button>
          </div>
        {{ form_end(form) }}
      </div>
    </div>
  </div>

  <p>{{ property.description | nl2br }}</p>

  <div class="row">
    <div class="col-md-8">
      <h2>Caractéristiques</h2>
      <table class="table table-striped">
        <tr>
          <td>Surface habitable</td>
          <td>{{ property.surface }} m²</td>
        </tr>
        <tr>
          <td>Pièces</td>
          <td>{{ property.rooms }}</td>
        </tr>
        <tr>
          <td>Chambres</td>
          <td>{{ property.bedrooms }}</td>
        </tr>
        <tr>
          <td>Etage</td>
          <td>{{ property.floor }}</td>
        </tr>
        <tr>
          <td>Chauffage</td>
          <td>{{ property.heatType }}</td>
        </tr>
      </table>
    </div>

    <div class="col-md-4">
      <h2>Spécificités</h2>
      <ul class="list-group">
        {% for option in property.options %}
          <li class="list-group-item">{{ option.name }}</li>
        {% endfor %}
      </ul>
    </div>

    <div id="map" style="width: 100%; height: 400px" class="mb-4"
      data-lat="{{ property.lat }}"
      data-lng="{{ property.lng }}"
    ></div>

  </div>
</div>
{% endblock %}